id: IFF7DDFD3
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3876-final
source_file: null
initial_creation_type: input
imported: '2022-07-27T11:52:21.064565'
last_modified: '2022-07-27T11:52:21.064585'
parser: null
source_metadata:
  title: ཐུན་མོང་གི་རྩ་བ།
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
